#!/usr/bin/env python3
"""
Multiple Choice Question refinement from QA pairs
"""
import json
import re
import random
from typing import Dict, Any, List, Tuple, Optional
from openai import OpenAI
try:
    from .utils import log_message, safe_get_response_content
except ImportError:
    import sys
    import os
    sys.path.append(os.path.dirname(__file__))
    from utils import log_message, safe_get_response_content


class MCQRefiner:
    """Refines QA pairs into multiple choice questions"""
    
    def __init__(self, api_key: str):
        self.client = OpenAI(
            api_key=api_key,
            base_url="https://openrouter.ai/api/v1"
        )
    
    def get_refinement_prompt(self) -> str:
        """Get the prompt template for QA refinement - keep original unchanged"""
        return """I have a Video Question Answering (VQA) pair that was generated by a large language model. The model watched a video and produced a question and an answer.

Here is the QA pair:
Question:
<question>
Answer:
<answer>

**Task Procedure:**
1. Carefully read and understand the provided VQA data. 
2. Rewrite the question so that:
 • it sounds like something a person would naturally ask in daily life
 • it can be answered succinctly
 • all descriptive modifiers as well as any time / location details from the original are fully preserved 
3. Convert the Answer into a multiple-choice question (MCQ) format with five options

**Requirements:**
1. The rewritten question must be phrased in a natural, conversational way that a human would use in daily life. It should not sound like a formal test question
2. You must create five options in total. One option must be the correct answer. The other four options must be incorrect distractors
3. These distractors should be challenging and highly plausible to confuse someone who has not paid close attention to the details. The distractors **MUST** be close in meaning to make them challenging
4. If the original question is inherently a Yes/No question, keep it in Yes/No form, but still generate five options. Each option should begin with "Yes," or "No," followed by a parallel detail

**Format Consistency**
All five answer options must be stylistically consistent. They should have a similar length, structure, and level of detail. This is to ensure one option doesn't stand out simply because of its format

Please only return the Question and five options, as well as the correct answer."""
    
    def extract_qa_from_response(self, llm_response: str) -> Tuple[str, str]:
        """Extract question and answer from LLM response"""
        try:
            # Look for Question and Answer patterns
            question_pattern = r"[Qq]uestion:\s*\n?(.*?)(?=\n[Aa]nswer:|$)"
            answer_pattern = r"[Aa]nswer:\s*\n?(.*?)(?=\n[Ee]vidence:|$)"
            
            question_match = re.search(question_pattern, llm_response, re.DOTALL)
            answer_match = re.search(answer_pattern, llm_response, re.DOTALL)
            
            if question_match and answer_match:
                question = question_match.group(1).strip()
                answer = answer_match.group(1).strip()
                
                log_message("Successfully extracted QA pair from response")
                return question, answer
            
            # Try alternative patterns
            lines = llm_response.split('\n')
            question = None
            answer = None
            
            for i, line in enumerate(lines):
                if line.strip().lower().startswith('question:'):
                    question = line.split(':', 1)[1].strip()
                    if i + 1 < len(lines):
                        question += " " + lines[i + 1].strip()
                elif line.strip().lower().startswith('answer:'):
                    answer = line.split(':', 1)[1].strip()
                    if i + 1 < len(lines):
                        answer += " " + lines[i + 1].strip()
            
            if question and answer:
                log_message("Extracted QA pair using alternative method")
                return question, answer
            
            log_message("Failed to extract QA pair")
            return "Could not extract question", "Could not extract answer"
            
        except Exception as e:
            log_message(f"Error extracting QA pair: {str(e)}")
            return "Extraction failed", "Extraction failed"
    
    def refine_to_mcq(self, question: str, answer: str) -> Optional[str]:
        """Refine QA pair to multiple choice question using structured output"""
        try:
            # Replace placeholders in prompt template
            prompt_template = self.get_refinement_prompt()
            prompt = prompt_template.replace("<question>", question).replace("<answer>", answer)
            
            # Define JSON Schema for structured output
            json_schema = {
                "name": "multiple_choice_question",
                "strict": True,
                "schema": {
                    "type": "object",
                    "properties": {
                        "question": {
                            "type": "string",
                            "description": "The refined question in natural, conversational language"
                        },
                        "option_a": {
                            "type": "string",
                            "description": "First answer option"
                        },
                        "option_b": {
                            "type": "string",
                            "description": "Second answer option"
                        },
                        "option_c": {
                            "type": "string",
                            "description": "Third answer option"
                        },
                        "option_d": {
                            "type": "string",
                            "description": "Fourth answer option"
                        },
                        "option_e": {
                            "type": "string",
                            "description": "Fifth answer option"
                        },
                        "correct_answer": {
                            "type": "string",
                            "description": "The letter of the correct answer (A, B, C, D, or E)"
                        }
                    },
                    "required": ["question", "option_a", "option_b", "option_c", "option_d", "option_e", "correct_answer"],
                    "additionalProperties": False
                }
            }
            
            log_message("Starting MCQ refinement with structured output")
            
            response = self.client.chat.completions.create(
                model="google/gemini-2.5-pro",
                messages=[
                    {
                        "role": "user",
                        "content": prompt
                    }
                ],
                response_format={
                    "type": "json_schema",
                    "json_schema": json_schema
                },
                temperature=1,
                max_tokens=65536
            )
            
            refined_response = safe_get_response_content(response)
            if refined_response:
                log_message("MCQ refinement completed")
                return refined_response
            else:
                log_message("Empty response from MCQ refinement")
                return None
                
        except Exception as e:
            log_message(f"MCQ refinement failed: {str(e)}")
            return None
    
    def parse_mcq_response(self, refined_response: str) -> Tuple[str, List[str], int]:
        """Parse JSON formatted MCQ response"""
        try:
            log_message("Parsing JSON MCQ response")
            
            # Clean response text and extract JSON
            cleaned_response = refined_response.strip()
            
            # Remove code block markers if present
            if cleaned_response.startswith('```'):
                json_match = re.search(r'```(?:json)?\s*\n?(.*?)\n?```', cleaned_response, re.DOTALL)
                if json_match:
                    cleaned_response = json_match.group(1).strip()
            
            # Extract JSON object
            brace_start = cleaned_response.find('{')
            if brace_start != -1:
                brace_count = 0
                brace_end = brace_start
                for i, char in enumerate(cleaned_response[brace_start:], brace_start):
                    if char == '{':
                        brace_count += 1
                    elif char == '}':
                        brace_count -= 1
                        if brace_count == 0:
                            brace_end = i
                            break
                cleaned_response = cleaned_response[brace_start:brace_end + 1]
            
            # Parse JSON
            parsed_data = json.loads(cleaned_response)
            
            # Extract fields
            refined_question = parsed_data.get('question', 'Failed to parse question')
            
            options = [
                parsed_data.get('option_a', 'Option A'),
                parsed_data.get('option_b', 'Option B'), 
                parsed_data.get('option_c', 'Option C'),
                parsed_data.get('option_d', 'Option D'),
                parsed_data.get('option_e', 'Option E')
            ]
            
            correct_answer_letter = parsed_data.get('correct_answer', 'A').upper()
            if correct_answer_letter in 'ABCDE':
                correct_index = ord(correct_answer_letter) - ord('A')
            else:
                correct_index = 0
            
            log_message(f"JSON parsing successful: {len(options)} options, correct answer = {correct_answer_letter}")
            
            return refined_question, options, correct_index
            
        except Exception as e:
            log_message(f"JSON parsing failed: {str(e)}")
            # Return default values
            return "Parsing failed", ["Option A", "Option B", "Option C", "Option D", "Option E"], 0
    
    def shuffle_options(self, options: List[str], correct_index: int) -> Tuple[List[str], int]:
        """Randomly shuffle options and return new correct index"""
        try:
            # Save correct answer
            correct_answer = options[correct_index]
            
            # Create and shuffle indices
            indices = list(range(len(options)))
            random.shuffle(indices)
            
            # Reorder options
            shuffled_options = [options[i] for i in indices]
            
            # Find new position of correct answer
            new_correct_index = shuffled_options.index(correct_answer)
            
            log_message(f"Options shuffled: correct answer moved from position {correct_index} to {new_correct_index}")
            
            return shuffled_options, new_correct_index
            
        except Exception as e:
            log_message(f"Option shuffling failed: {str(e)}")
            return options, correct_index
    
    def process_qa_to_mcq(self, qa_response: str) -> Dict[str, Any]:
        """Complete process: extract QA, refine to MCQ, shuffle options"""
        # Extract QA from response
        question, answer = self.extract_qa_from_response(qa_response)
        
        if question == "Could not extract question":
            log_message("Skipping MCQ refinement due to extraction failure")
            return {
                'success': False,
                'error': 'Failed to extract QA pair',
                'original_question': question,
                'original_answer': answer
            }
        
        # Refine to MCQ
        refined_response = self.refine_to_mcq(question, answer)
        
        if not refined_response:
            log_message("MCQ refinement failed")
            return {
                'success': False,
                'error': 'MCQ refinement failed',
                'original_question': question,
                'original_answer': answer
            }
        
        # Parse MCQ response
        refined_question, options, correct_index = self.parse_mcq_response(refined_response)
        
        # Shuffle options
        shuffled_options, new_correct_index = self.shuffle_options(options, correct_index)
        
        return {
            'success': True,
            'original_question': question,
            'original_answer': answer,
            'refined_question': refined_question,
            'options': shuffled_options,
            'correct_answer_index': new_correct_index,
            'correct_answer_letter': chr(65 + new_correct_index),
            'raw_refined_response': refined_response
        }


def main():
    """Test MCQ refinement functionality"""
    import argparse
    
    parser = argparse.ArgumentParser(description='Test MCQ refiner')
    parser.add_argument('--api-key', required=True, help='OpenRouter API key')
    parser.add_argument('--question', required=True, help='Test question')
    parser.add_argument('--answer', required=True, help='Test answer')
    
    args = parser.parse_args()
    
    # Test MCQ refinement
    refiner = MCQRefiner(args.api_key)
    
    try:
        # Test direct QA to MCQ
        refined_response = refiner.refine_to_mcq(args.question, args.answer)
        
        if refined_response:
            log_message("Raw refinement response:")
            print(refined_response)
            
            # Parse response
            refined_question, options, correct_index = refiner.parse_mcq_response(refined_response)
            
            log_message("Parsed MCQ:")
            print(f"Question: {refined_question}")
            print("Options:")
            for i, option in enumerate(options):
                marker = " ✓" if i == correct_index else ""
                print(f"  {chr(65+i)}) {option}{marker}")
            print(f"Correct Answer: {chr(65+correct_index)}")
            
            # Test shuffling
            shuffled_options, new_correct_index = refiner.shuffle_options(options, correct_index)
            
            log_message("After shuffling:")
            for i, option in enumerate(shuffled_options):
                marker = " ✓" if i == new_correct_index else ""
                print(f"  {chr(65+i)}) {option}{marker}")
            print(f"Correct Answer: {chr(65+new_correct_index)}")
            
        else:
            log_message("MCQ refinement failed")
            
    except Exception as e:
        log_message(f"MCQ refinement test failed: {str(e)}")


if __name__ == "__main__":
    main() 